SIS_ITELEC3/SIS_ITELEC3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SIS_ITELEC3.Controllers
{
    [AllowAnonymous]  //accessible
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SIS_ITELEC3/SIS_ITELEC3/Controllers/api/GradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using AutoMapper;
using SIS_ITELEC3.Dtos;
using SIS_ITELEC3.Models;
using System.Data.Entity;

namespace SIS_ITELEC3.Controllers.api
{
    public class GradesController : ApiController
    {
        private ApplicationDbContext _context;

        public GradesController()
        {
            _context = new ApplicationDbContext();

        }

        [HttpGet]
        public IHttpActionResult GetGrades()
        {
            var gradesDto = _context.Grades
                .Include(g => g.Student)
                .Include(g => g.Subject)
                .ToList()
                .Select(Mapper.Map<Grades, GradesDto>);
            return Ok(gradesDto);
        }

        [HttpGet]
        public IHttpActionResult GetGrade(int id)
        {
            var grade = _context.Grades.SingleOrDefault(g => g.Id == id);
            if (grade == null)
                return NotFound();
            var gradeDto = Mapper.Map<Grades, GradesDto>(grade);
            return Ok(gradeDto);
        }

        [HttpPost]
        public IHttpActionResult CreateGrade(GradesDto gradeDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var grade = Mapper.Map<GradesDto, Grades>(gradeDto);

            _context.Grades.Add(grade);
            _context.SaveChanges();

            gradeDto.Id = grade.Id;

            return Created(new Uri(Request.RequestUri + "/" + grade.Id), gradeDto);
        }

        [HttpPut]
        public void UpdateCourse(int id, GradesDto gradeDto)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var gradeInDb = _context.Grades.SingleOrDefault(g => g.Id == id);

            if (gradeInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            Mapper.Map(gradeDto, gradeInDb);

            _context.SaveChanges();

        }

        [HttpDelete]
        public void DeleteGrades(int id)
        {
            var gradeInDB = _context.Grades.SingleOrDefault(g => g.Id == id);
            if (gradeInDB == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            _context.Grades.Remove(gradeInDB);
            _context.SaveChanges();
        }
    }
}

SIS_ITELEC3/SIS_ITELEC3/Controllers/api/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using AutoMapper;
using SIS_ITELEC3.Dtos;
using SIS_ITELEC3.Models;
using System.Data.Entity;

namespace SIS_ITELEC3.Controllers.api
{
    public class StudentsController : ApiController
    {
        private ApplicationDbContext _context;

        public StudentsController()
        {
            _context = new ApplicationDbContext();

        }

        [HttpGet]
        public IHttpActionResult GetStudents()
        {
            var studentsDto = _context.Students
                .Include(s => s.Course)
                .ToList()
                .Select(Mapper.Map<Students, StudentsDto>);
            return Ok(studentsDto);
        }

        [HttpGet]
        public IHttpActionResult GetStudent(int id)
        {
            var student = _context.Students.SingleOrDefault(s => s.Id == id);
            if (student == null)
                return NotFound();
            var studentDto = Mapper.Map<Students, StudentsDto>(student);
            return Ok(studentDto);
        }

        [HttpPost]
        public IHttpActionResult CreateStuden(StudentsDto studentDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var student = Mapper.Map<StudentsDto, Students>(studentDto);

            _context.Students.Add(student);
            _context.SaveChanges();

            studentDto.Id = student.Id;

            return Created(new Uri(Request.RequestUri + "/" + student.Id), studentDto);
        }

        [HttpPut]
        public void UpdateStudent(int id, StudentsDto studentDto)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var studentInDb = _context.Students.SingleOrDefault(s => s.Id == id);

            if (studentInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            Mapper.Map(studentDto, studentInDb);

            _context.SaveChanges();

        }

        [HttpDelete]
        public void DeleteStudent(int id)
        {
            var studentInDB = _context.Students.SingleOrDefault(s => s.Id == id);
            if (studentInDB == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            _context.Students.Remove(studentInDB);
            _context.SaveChanges();
        }
    }
}

SIS_ITELEC3/SIS_ITELEC3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SIS_ITELEC3/SIS_ITELEC3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SIS_ITELEC3/SIS_ITELEC3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-6 d-flex flex-column justify-content-center">
                <h4>Help Students Reach Their Potential</h4>
                <h1>Student Information System</h1>
                <p class="text-tertiary">Maging kabalikat sa pag-aaral</p>
                <a href="http://go.microsoft.com/fwlink/?LinkId=301865" class="btn btn-primary mb-4">Learn More</a>
            </div>
            <div class="col-md-6 d-flex justify-content-end align-items-end">
                
                    <div >
                        <img src="@Url.Content("~/Images/student.png")" width="500" class="img-fluid mx-auto d-block">
                    </div>
                </div>
        </div>
    </div>
</div>

<br />
<div class="container" style="margin-bottom:60px">
    <h1 class="text-center">An easy-to-use Student Information System</h1>
    <br />
    <div class="row d-flex text-capitalize text-center">
        <div class="col-lg-3">
            <img src="@Url.Content("~/Images/reading.png")" alt="">
            <h6 class="row-cs-text">Effortlessly organize student information</h6>
            @Html.ActionLink("See more", "Index", "Students", null, new { @class = "btn btn-primary btn-sm" })
        </div>
        <div class="col-lg-3">
            <img src="@Url.Content("~/Images/test.png")" alt="">
            <h6 class="row-cs-text">Efficiently track and manage student grades</h6>
            @Html.ActionLink("See more", "Index", "Grades", null, new { @class = "btn btn-primary btn-sm" })
        </div>
        <div class="col-lg-3">
            <img src="@Url.Content("~/Images/books-stack-of-three.png")" alt="">
            <h6 class="row-cs-text">Seamlessly oversee subjects and courses</h6>
            @Html.ActionLink("See more", "Index", "Subjects", null, new { @class = "btn btn-primary btn-sm" })
        </div>
        <div class="col-lg-3">
            <img src="@Url.Content("~/Images/male.png")" alt="">
            <h6 class="row-cs-text">Easily add and manage instructors</h6>
            @Html.ActionLink("See more", "Index", "Instructor", null, new { @class = "btn btn-primary btn-sm" })
        </div>
    </div>
</div>